Add new model type 'replacement then uninstallation'
pluginsGLPI/uninstall pull request #110
Opened 2024-07-22 11:59 UTC by ArthurMinfotel

Combination of both existing model types in one.

2024-08-20 12:58 UTC, stonebuzz commented
Hi @ArthurMinfotel 

If I understand correctly, the new mode allows you to replace an asset with a new one and then uninstall the first?

2024-08-21 08:38 UTC, ArthurMinfotel commented
> Hi @ArthurMinfotel
> 
> If I understand correctly, the new mode allows you to replace an asset with a new one and then uninstall the first?

That's exactly it. A typical use case would be : I want to replace computer A by computer B, then put A back in stock.
Right now it would be done by applying a replace type model to A to replace by B, then applying a uninstall type model to A. This is meant to unable doing both action in one go.

2024-08-21 09:24 UTC, stonebuzz commented
When the plugin is installed, two models are created by default.

![image](https://github.com/user-attachments/assets/298fd927-6cb3-43a4-b364-44cc2dceaf1a)

A third model would have to be created during the update (or fresh install) to represent this new mode.

2024-08-21 11:52 UTC, ArthurMinfotel commented
> When the plugin is installed, two models are created by default.
> 
> ![image](https://private-user-images.githubusercontent.com/7335054/359836341-298fd927-6cb3-43a4-b364-44cc2dceaf1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDEzMDQsIm5iZiI6MTcyNDI0MTAwNCwicGF0aCI6Ii83MzM1MDU0LzM1OTgzNjM0MS0yOThmZDkyNy02Y2IzLTQzYTQtYjM2NC00NGNjMmRjZWFmMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTE1MDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU1MjhmMzMwNjgyOGU5MTk4YzZiNzFlM2FjOTc5MDNjYTU5MzA2OWE4NzBiNDE3YTVmYzg1NzM1ZmM0ZTZmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b_dn80wYwrUzVoIGrjbY_dGP9FhrbLsgCiUA3LbGPxY)
> 
> A third model would have to be created during the update (or fresh install) to represent this new mode.

It's done.
![image](https://github.com/user-attachments/assets/35f5af83-900d-4a03-9d2d-8fd3e61fddf5)

2024-08-21 12:06 UTC, stonebuzz approved these changes

2024-08-21 12:35 UTC, Rom1-B requested changes

2024-08-21 12:35 UTC, Rom1-B commented on inc/model.class.php
> +                    __("The purge archiving method is not available for this type of model", 'uninstall'),
```suggestion
                    __("The purge archiving method is not available for this model type", 'uninstall'),
```

2024-08-21 12:35 UTC, Rom1-B commented on inc/model.class.php
>      * @param $value  default value (default '')
```suggestion
    * @param $value  default value (default '')
    * @param $type   int types_id
```

2024-08-21 12:35 UTC, Rom1-B commented on inc/model.class.php
> +        }
A switch/case would probably be more suitable

2024-08-21 14:25 UTC, Rom1-B approved these changes

2024-08-21 14:26 UTC, merged