feat(uninstall): delete inventory data
pluginsGLPI/uninstall pull request #73
Opened 2022-10-12 07:38 UTC by Rom1-B

Adds an option to delete inventory data:
- unlock fields
- native agent
- elements linked to the agent if the `glpiinventory` plugin is active

ref: !25150

2022-10-13 12:42 UTC, cedric-anne requested changes

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +            self::deleteGlpiInventoryLink($type, $id);
```suggestion
            self::deleteGlpiInventoryLink($item);
```

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +    * @param $items_id the asset's ID in GLPI
```suggestion
    * @param CommonDBTM $item
```

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +   static function deleteGlpiInventoryLink($itemtype, $items_id) {
```suggestion
   static function deleteGlpiInventoryLink(CommonDBTM $item) {
```

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +
```suggestion
```

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +         self::purgeAgents($itemtype, $items_id);
No need to split this into many methods.
```suggestion
         $agent = new Agent();
         $agent->deleteByCriteria([
            'itemtype' => $item->getType(),
            'items_id' => $item->getID(),
         ]);
```

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +      self::purgeLockedField($itemtype, $items_id);
There is already a method for this.

```suggestion
     $lockedfield = new Lockedfield();
     if ($lockedfield->isHandled($item)) {
         $lockedfield->itemDeleted();
     }
```

2022-10-13 12:42 UTC, cedric-anne commented on inc/uninstall.class.php
> +   }
```suggestion
```

2022-10-13 12:42 UTC, cedric-anne commented on setup.php
> +define ('PLUGIN_UNINSTALL_VERSION', '2.8.1');
Will be do during release process.

```suggestion
define ('PLUGIN_UNINSTALL_VERSION', '2.8.0');
```

2022-10-13 13:06 UTC, cedric-anne commented on inc/uninstall.class.php
> +            self::deleteGlpiInventoryLink($type, $id);
You missed this one.

2022-10-13 13:14 UTC, cedric-anne commented on inc/model.class.php
> +                           ? $this->fields["raz_glpiinventory"] : 0), -1, ['width' => '100%']);
This is not define for other fields, so I guess it should not be for this one.
```suggestion
                           ? $this->fields["raz_glpiinventory"] : 0), -1);
```

2022-10-17 13:42 UTC, stonebuzz commented
unless I am wrong, several elements are missing from ```relation.constant.php```

![Uploading image.png…]()

We need (at least) : 

```php
'glpi_monitors'    => 'computers_id',
'glpi_networkports'    => ['items_id', 'itemtype'],
'glpi_networkname'    => ['items_id', 'itemtype'],
'glpi_ipaddresses'    => ['mainitems_id', 'mainitemtype'],
'glpi_items_operatingsystems'    => ['items_id', 'itemtype'],
'glpi_items_disks'    => ['items_id', 'itemtype'],
'glpi_items_devicebatteries'    => ['items_id', 'itemtype'],
//all related item like glpi_items_devicexxxxxxx
```

2022-10-17 14:02 UTC, Rom1-B commented
> unless I am wrong, several elements are missing from `relation.constant.php`
> 
> ![image](https://user-images.githubusercontent.com/7335054/196193176-648001b7-9413-4c2d-b34a-c2df7d2b4e8a.png)
> 
> We need (at least) :
> 
> ```
> 'glpi_monitors'                             => 'computers_id',
> 'glpi_networkports'                      => ['items_id', 'itemtype'],
> 'glpi_networkname'                     => ['items_id', 'itemtype'],
> 'glpi_ipaddresses'                       => ['mainitems_id', 'mainitemtype'],
> 'glpi_items_operatingsystems'    => ['items_id', 'itemtype'],
> 'glpi_items_disks'                        => ['items_id', 'itemtype'],
> 'glpi_items_devicebatteries'        => ['items_id', 'itemtype'],
> //all related item like glpi_items_devicexxxxxxx
> ```

The link seems to be via '_glpi_computers_items'.

2022-10-17 14:10 UTC, stonebuzz commented
```_glpi_computers_items``` handle only

```$CFG_GLPI["directconnect_types"]          = ['Monitor', 'Peripheral', 'Phone', 'Printer'];```

2022-10-18 12:07 UTC, trasher approved these changes

2022-10-18 13:32 UTC, cedric-anne requested changes

2022-10-18 13:32 UTC, cedric-anne commented on inc/uninstall.class.php
> +            }
Technically, you may have an array containing 2 distinct foreign keys, for instance
```php
    'glpi_groups' => [
        'glpi_certificates'          => [
            'groups_id_tech',
            'groups_id',
        ],
```
, also, you cannot be sure that `itemtype` and `items_id` are declared in the correct order.


```suggestion
            if (
               is_array($field)
               && count($itemtype_match = preg_grep('/itemtype/', $field)) === 1
               && count($items_id_match = preg_grep('/items_id/', $field)) === 1
            ) {
               $DB->update(
                  $tablename,
                  [
                     'is_deleted' => 0
                  ],
                  [
                     $items_id_match[0] => $item->getID(),
                     $itemtype_match[1] => $item->getType(),
                     'is_dynamic' => 1
                  ]
               );
            } else {
               if (!is_array($field)) {
                  $field = [$field];
               }
               foreach ($field as $f) {
                  $DB->update(
                     $tablename,
                     [
                        'is_deleted' => 0
                     ],
                     [
                        $f => $item->getID(),
                        'is_dynamic' => 1
                     ]
                  );
               }
            }
```

2022-10-18 13:32 UTC, cedric-anne commented on inc/uninstall.class.php
> +         foreach ($RELATION[$item->getTable()] as $tablename => $field) {
You should verify if related items have a `is_dynamic` property (can be done using `CommonDBTM::canBeDynamic()`.

2022-10-24 13:57 UTC, cedric-anne commented
Will be strongly impacted by https://github.com/glpi-project/glpi/pull/13018

2023-06-20 19:39 UTC, cedric-anne commented
@stonebuzz 

Can you check this PR ?

2023-06-20 19:39 UTC, cedric-anne approved these changes

2023-06-21 06:25 UTC, stonebuzz requested changes

2023-06-21 06:25 UTC, stonebuzz commented on inc/uninstall.class.php
> +                  );
SQL error trigger here

```shell
[2023-06-21 08:20:34] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/TECLIB/DEV/GLPI/10.0-bugfixes/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: UPDATE `glpi_ipaddresses` SET `is_deleted` = '0', `is_dynamic` = '0' WHERE (Computer) AND `is_dynamic` = '1'
  Error: Unknown column 'Computer' in 'where clause'
  Backtrace :
  src/DBmysql.php:1461                               
  plugins/uninstall/inc/uninstall.class.php:608      DBmysql->update()
  plugins/uninstall/inc/uninstall.class.php:123      PluginUninstallUninstall::deleteGlpiInventoryLink()
  plugins/uninstall/inc/uninstall.class.php:333      PluginUninstallUninstall::doOneUninstall()
  plugins/uninstall/front/action.php:76              PluginUninstallUninstall::uninstall()
  {"user":"2@stanislas-asus-desktop"} 
```

2023-06-21 06:25 UTC, stonebuzz commented on inc/uninstall.class.php
> +
Some data / link are not purged

![image](https://github.com/pluginsGLPI/uninstall/assets/7335054/5a831d22-7edc-4053-8bc2-6820625f6e3e)

2023-06-21 07:46 UTC, stonebuzz approved these changes

2023-06-21 07:47 UTC, cedric-anne commented on inc/uninstall.class.php
> +   static function deleteGlpiInventoryLink(&$item) {
Objects are always passed by reference.
```suggestion
   static function deleteGlpiInventoryLink($item) {
```

2023-06-30 12:35 UTC, merged